### ISSUE TITLE
[스파크] 추천 알고리즘 | 6mini.log

### ISSUE THREAD

**Issue by 6mini** [6mini/6mini.github.io#171]
https://6mini.github.io/data%20engineering/2021/12/24/recoalgo/ 

 스파크의 추천 알고리즘과 ALS(Alternating Least Squares)의 개념. 영화 추천 파이프라인 예제

**Comment by 6mini** [comment]
test

**Comment by 6mini** [comment]
hi

**Comment by ssu-jeong** [comment]
hi
